// <auto-generated />
using System;
using MangoParser.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MangoParser.Migrations
{
    [DbContext(typeof(MangoParserDbContext))]
    partial class MangoParserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MangoParser.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genre_id_pk");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MangoParser.Data.Models.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("en_name");

                    b.Property<DateTime>("LastCheckout")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checkout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RuName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ru_name");

                    b.HasKey("Id")
                        .HasName("manga_id_pk");

                    b.ToTable("mangas", (string)null);
                });

            modelBuilder.Entity("MangoParser.Data.Models.Rating", b =>
                {
                    b.Property<int>("MangaId")
                        .HasColumnType("integer")
                        .HasColumnName("manga_id");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric")
                        .HasColumnName("average_rating");

                    b.Property<int>("VotesCount")
                        .HasColumnType("integer")
                        .HasColumnName("votes_count");

                    b.HasKey("MangaId")
                        .HasName("rating_id_pk");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("MangoParser.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tag_id_pk");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("manga_genre_ref", b =>
                {
                    b.Property<int>("manga_id")
                        .HasColumnType("integer");

                    b.Property<int>("genre_id")
                        .HasColumnType("integer");

                    b.HasKey("manga_id", "genre_id")
                        .HasName("manga_ganre_pk");

                    b.HasIndex(new[] { "genre_id", "manga_id" }, "IX_manga_ganre_ref");

                    b.ToTable("manga_ganre_ref", (string)null);
                });

            modelBuilder.Entity("manga_tag_ref", b =>
                {
                    b.Property<int>("manga_id")
                        .HasColumnType("integer");

                    b.Property<int>("tag_id")
                        .HasColumnType("integer");

                    b.HasKey("manga_id", "tag_id")
                        .HasName("manga_tag_pk");

                    b.HasIndex("tag_id");

                    b.HasIndex(new[] { "manga_id", "tag_id" }, "IX_manga_tag_ref");

                    b.ToTable("manga_tag_ref", (string)null);
                });

            modelBuilder.Entity("MangoParser.Data.Models.Rating", b =>
                {
                    b.HasOne("MangoParser.Data.Models.Manga", "Manga")
                        .WithOne("Rating")
                        .HasForeignKey("MangoParser.Data.Models.Rating", "MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("rating_manga_id_fk");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("manga_genre_ref", b =>
                {
                    b.HasOne("MangoParser.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoParser.Data.Models.Manga", null)
                        .WithMany()
                        .HasForeignKey("manga_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("manga_tag_ref", b =>
                {
                    b.HasOne("MangoParser.Data.Models.Manga", null)
                        .WithMany()
                        .HasForeignKey("manga_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoParser.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangoParser.Data.Models.Manga", b =>
                {
                    b.Navigation("Rating")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
